version: '3.4'

networks:
  cors_dev:
    external: true

services:
  db:
    image: mysql:8
    container_name: coreshop-datahub-demo
    networks:
      - cors_dev
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore

  php:
    build:
      context: ./
      target: cors_php
      args:
        - COMPOSER_AUTH=${COMPOSER_AUTH}
    container_name: coreshop-datahub-demo-php
    networks:
      - cors_dev
    depends_on:
     - db
    environment:
      - DATABASE_DRIVER=pdo_mysql
      - DATABASE_HOST=coreshop-datahub-demo
      - DATABASE_PORT=3306
      - DATABASE_NAME=pimcore
      - DATABASE_USER=pimcore
      - DATABASE_PASSWORD=pimcore
      - DATABASE_VERSION=8.0.26
      - PIMCORE_INSTALL_ADMIN_USERNAME=admin
      - PIMCORE_INSTALL_ADMIN_PASSWORD=admin

  nginx:
    build:
      context: ./
      target: cors_nginx
      args:
          - COMPOSER_AUTH=${COMPOSER_AUTH}
    container_name: coreshop-datahub-nginx
    depends_on:
        - php
    volumes:
        - .docker/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cors_dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.coreshop_datahub_demo.rule=Host(`coreshop-datahub-demo.localhost`)
      - traefik.http.routers.coreshop_datahub_demo.entrypoints=cors_dev
      - traefik.http.routers.coreshop_datahub_demo.tls=true
      - traefik.http.services.coreshop_datahub_demo.loadbalancer.server.port=80
      - traefik.docker.network=cors_dev
