pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    coreshop_productDetailThumbnail:
                        items:
                            -
                                method: contain
                                arguments:
                                    width: 150
                                    height: 150
                            -
                                method: frame
                                arguments:
                                    width: 150
                                    height: 150
                        medias: {  }
                        name: coreshop_productDetailThumbnail
                        description: ''
                        group: CoreShop
                        format: SOURCE
                        quality: 90
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1688643691
                        creationDate: 1688643691
                        preserveAnimation: false
