imports:
    - { resource: services.yaml }
    - { resource: pimcore.yaml }
    - { resource: 'local/' }

doctrine:
    dbal:
        connections:
            default:
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                dbname: '%env(DATABASE_NAME)%'
                host: '%env(DATABASE_HOST)%'
                port: '%env(DATABASE_PORT)%'
                server_version: '%env(DATABASE_VERSION)%'
                mapping_types: { enum: enum, bit: boolean }

pimcore_studio_backend:
    mercure_settings:
        jwt_key: 'wrMZk0YSUABq3GuSGKcxmjAZXv9lJYB3'
        hub_url_client: 'https://coreshop-coreshop4-demo-mercure.localhost/.well-known/mercure'
        hub_url_server: 'http://mercure/.well-known/mercure'

pimcore:
    product_registration:
        instance_identifier: '%env(PIMCORE_INSTANCE_IDENTIFIER)%'
        product_key: '%env(PIMCORE_PRODUCT_KEY)%'
    encryption:
        secret: '%env(PIMCORE_ENCRYPTION_SECRET)%'