pimcore_data_hub:
    configurations:
        coreshop:
            general:
                active: true
                type: coreshop_graphql
                name: coreshop
                description: ''
                group: ''
                sqlObjectCondition: ''
                modificationDate: 1688450462
                path: null
                createDate: 1688116542
            schema:
                queryEntities:
                    CoreShopOrder:
                        id: CoreShopOrder
                        name: CoreShopOrder
                        columnConfig:
                            columns:
                                -
                                    attributes:
                                        attribute: token
                                        label: Token
                                        dataType: input
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: store
                                        label: Store
                                        dataType: coreShopStore
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: items
                                        label: Items
                                        dataType: coreShopRelations
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: customer
                                        label: coreshop.order.customer
                                        dataType: coreShopRelation
                                    isOperator: false
                    CoreShopOrderItem:
                        id: CoreShopOrderItem
                        name: CoreShopOrderItem
                        columnConfig:
                            columns:
                                -
                                    attributes:
                                        attribute: quantity
                                        label: Quantity
                                        dataType: numeric
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: product
                                        label: coreshop.order_item.product
                                        dataType: coreShopRelation
                                    isOperator: false
                    CoreShopProduct:
                        id: CoreShopProduct
                        name: CoreShopProduct
                        columnConfig:
                            columns:
                                -
                                    attributes:
                                        attribute: name
                                        label: Name
                                        dataType: input
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: shortDescription
                                        label: 'Short Description'
                                        dataType: textarea
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: slug
                                        label: Slug
                                        dataType: urlSlug
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: sku
                                        label: SKU
                                        dataType: input
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: ean
                                        label: EAN13
                                        dataType: input
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: active
                                        label: Active
                                        dataType: checkbox
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: digitalProduct
                                        label: 'Digital Product'
                                        dataType: booleanSelect
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: manufacturer
                                        label: Manufacturer
                                        dataType: coreShopRelation
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: pimcoreMetaTitle
                                        label: 'Meta Title'
                                        dataType: input
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: pimcoreMetaDescription
                                        label: 'Meta Description'
                                        dataType: textarea
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: description
                                        label: Description
                                        dataType: wysiwyg
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: mainVariant
                                        label: 'Main Variant'
                                        dataType: coreShopRelation
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: allowedAttributeGroups
                                        label: 'Allowed attribute groups'
                                        dataType: coreShopRelations
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: attributes
                                        label: Attributes
                                        dataType: coreShopRelations
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: categories
                                        label: Category
                                        dataType: coreShopRelations
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: images
                                        label: Images
                                        dataType: manyToManyRelation
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: onHold
                                        label: 'On Hold'
                                        dataType: numeric
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: onHand
                                        label: 'On Hand'
                                        dataType: numeric
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: isTracked
                                        label: 'Is Tracked'
                                        dataType: booleanSelect
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: minimumQuantityToOrder
                                        label: 'Min to Order'
                                        dataType: numeric
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: maximumQuantityToOrder
                                        label: coreshop.product.maximal_quantity_to_order
                                        dataType: numeric
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: unitDefinitions
                                        label: 'Unit Definitions'
                                        dataType: coreShopProductUnitDefinitions
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: storeValues
                                        label: coreshop.product.store_values
                                        dataType: coreShopStoreValues
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: itemQuantityFactor
                                        label: 'Quantity Factor'
                                        dataType: numeric
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: wholesalePrice
                                        label: 'Wholesale Price'
                                        dataType: coreShopMoney
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: weight
                                        label: Weight
                                        dataType: numeric
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: height
                                        label: Height
                                        dataType: numeric
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: width
                                        label: Width
                                        dataType: numeric
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: depth
                                        label: Depth
                                        dataType: numeric
                                    isOperator: false
                    CoreShopUser:
                        id: CoreShopUser
                        name: CoreShopUser
                        columnConfig:
                            columns:
                                -
                                    attributes:
                                        attribute: loginIdentifier
                                        label: 'Login Identifier'
                                        dataType: input
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: customer
                                        label: Customer
                                        dataType: coreShopRelation
                                    isOperator: false
                    CoreShopCustomer:
                        id: CoreShopCustomer
                        name: CoreShopCustomer
                        columnConfig:
                            columns:
                                -
                                    attributes:
                                        attribute: firstname
                                        label: coreshop.customer.firstname
                                        dataType: firstname
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: lastname
                                        label: coreshop.customer.lastname
                                        dataType: lastname
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: email
                                        label: coreshop.customer.email
                                        dataType: email
                                    isOperator: false
                    CoreShopCategory:
                        id: CoreShopCategory
                        name: CoreShopCategory
                        columnConfig:
                            columns:
                                -
                                    attributes:
                                        attribute: name
                                        label: Name
                                        dataType: input
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: description
                                        label: Description
                                        dataType: textarea
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: slug
                                        label: Slug
                                        dataType: urlSlug
                                    isOperator: false
                                -
                                    attributes:
                                        attribute: parentCategory
                                        label: coreshop.category.parent_category
                                        dataType: coreShopRelation
                                    isOperator: false
                mutationEntities:
                    CoreShopOrder:
                        id: CoreShopOrder
                        name: CoreShopOrder
                        update: false
                    CoreShopUser:
                        id: CoreShopUser
                        name: CoreShopUser
                        update: false
                specialEntities:
                    document:
                        read: false
                        create: false
                        update: false
                        delete: false
                    document_folder:
                        read: false
                        create: false
                        update: false
                        delete: false
                    asset:
                        read: true
                        create: false
                        update: false
                        delete: false
                    asset_folder:
                        read: false
                        create: false
                        update: false
                        delete: false
                    asset_listing:
                        read: false
                        create: false
                        update: false
                        delete: false
                    object_folder:
                        read: false
                        create: false
                        update: false
                        delete: false
                    translation:
                        read: false
                        create: false
                        update: false
                        delete: false
                    translation_listing:
                        read: false
                        create: false
                        update: false
                        delete: false
                    coreshop_frontend:
                        read: true
                        create: false
                        update: false
                        delete: false
            security:
                method: datahub_apikey
                apikey:
                    - cccffae4fb6834f6a3d7eef35e890777
                skipPermissionCheck: false
                disableIntrospection: false
            workspaces:
                asset:
                    -
                        read: true
                        cpath: /
                        create: false
                        update: false
                        delete: false
                        id: extModel519-1
                document: {  }
                object:
                    -
                        read: true
                        cpath: /
                        create: true
                        update: true
                        delete: false
                        id: extModel535-1
            permissions:
                user: {  }
                role: {  }
