pimcore_static_routes:
    definitions:
        coreshop_checkout_do:
            name: coreshop_checkout_do
            pattern: /(\w+)\/shop\/checkout-do$/
            reverse: /%_locale/shop/checkout-do
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CheckoutController::doCheckoutAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643688
            modificationDate: 1688643688
