pimcore_static_routes:
    definitions:
        coreshop_cart_add:
            name: coreshop_cart_add
            pattern: '/(\w+)\/shop\/cart\/add\/([0-9]+)$/'
            reverse: /%%_locale/shop/cart/add/%%product
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CartController::addItemAction'
            variables: '_locale,product'
            defaults: null
            siteId: {  }
            methods:
                - POST
            priority: 3
            creationDate: 1688643688
            modificationDate: 1688643688
