pimcore_static_routes:
    definitions:
        coreshop_search:
            name: coreshop_search
            pattern: /(\w+)\/shop\/search$/
            reverse: /%_locale/shop/search
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\SearchController::searchAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643689
            modificationDate: 1688643689
