pimcore_static_routes:
    definitions:
        coreshop_quote_detail:
            name: coreshop_quote_detail
            pattern: '/(\w+)\/shop\/quote\~q([0-9]+)$/'
            reverse: /%%_locale/shop/quote~q%%quote
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\QuoteController::showAction'
            variables: '_locale,quote'
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643688
            modificationDate: 1688643688
