pimcore_static_routes:
    definitions:
        coreshop_cart_remove_price_rule:
            name: coreshop_cart_remove_price_rule
            pattern: /(\w+)\/shop\/cart\/remove-price-rule$/
            reverse: /%_locale/shop/cart/remove-price-rule
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CartController::removePriceRuleAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 3
            creationDate: 1688643688
            modificationDate: 1688643688
