pimcore_static_routes:
    definitions:
        coreshop_switch_currency:
            name: coreshop_switch_currency
            pattern: '/(\w+)\/shop\/switch-currency\/(.*)$/'
            reverse: /%%_locale/shop/switch-currency/%%currencyCode
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CurrencyController::switchAction'
            variables: '_locale,currencyCode'
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643688
            modificationDate: 1688643688
