pimcore_static_routes:
    definitions:
        coreshop_customer_change_password:
            name: coreshop_customer_change_password
            pattern: /(\w+)\/shop\/customer\/change-password$/
            reverse: /%_locale/shop/customer/change-password
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CustomerController::changePasswordAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643689
            modificationDate: 1688643689
