pimcore_static_routes:
    definitions:
        coreshop_customer_address_edit:
            name: coreshop_customer_address_edit
            pattern: '/(\w+)\/shop\/customer\/address\/(.*?)\~a([0-9]+)$/'
            reverse: /%%_locale/shop/customer/address/%%name~a%address
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CustomerController::addressAction'
            variables: '_locale,name,address'
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643689
            modificationDate: 1688643689
