pimcore_static_routes:
    definitions:
        coreshop_index:
            name: coreshop_index
            pattern: '/(\w+)\/shop(\/?)$/'
            reverse: /%_locale/shop
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\IndexController::indexAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 1
            creationDate: 1688643688
            modificationDate: 1688643688
