pimcore_static_routes:
    definitions:
        coreshop_payment_token:
            name: coreshop_payment_token
            pattern: '/(\w+)\/shop\/pay\/(.*)$/'
            reverse: /%%_locale/shop/pay/%%token
            controller: 'CoreShop\Bundle\PayumBundle\Controller\PaymentController::prepareCaptureAction'
            variables: '_locale,token'
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 1
            creationDate: 1706037383
            modificationDate: 1706037383
