pimcore_static_routes:
    definitions:
        coreshop_login_check:
            name: coreshop_login_check
            pattern: /(\w+)\/shop\/login-check$/
            reverse: /%_locale/shop/login-check
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\SecurityController::checkAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 3
            creationDate: 1688643688
            modificationDate: 1688643688
