pimcore_static_routes:
    definitions:
        coreshop_register:
            name: coreshop_register
            pattern: /(\w+)\/shop\/register$/
            reverse: /%_locale/shop/register
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\RegisterController::registerAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643689
            modificationDate: 1688643689
