pimcore_static_routes:
    definitions:
        coreshop_customer_confirm_newsletter:
            name: coreshop_customer_confirm_newsletter
            pattern: /(\w+)\/shop\/customer\/confirm-newsletter$/
            reverse: /%_locale/shop/customer/confirm-newsletter
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CustomerController::confirmNewsletterAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643689
            modificationDate: 1688643689
