pimcore_static_routes:
    definitions:
        coreshop_customer_password_reset_request:
            name: coreshop_customer_password_reset_request
            pattern: /(\w+)\/shop\/password-reset-request$/
            reverse: /%_locale/shop/password-reset-request
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\RegisterController::passwordResetRequestAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 6
            creationDate: 1688643689
            modificationDate: 1688643689
