pimcore_static_routes:
    definitions:
        coreshop_partial_cart_add:
            name: coreshop_partial_cart_add
            pattern: '/(\w+)\/_partial\/cart\/add\/([0-9]+)$/'
            reverse: /%%_locale/_partial/cart/add/%%product
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CartController::addItemAction'
            variables: '_locale,product'
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 3
            creationDate: 1688643688
            modificationDate: 1688643688
