pimcore_static_routes:
    definitions:
        coreshop_order_revise_pay:
            name: coreshop_order_revise_pay
            pattern: '/(\w+)\/shop\/order\/revise\/(.*)\/pay$/'
            reverse: /%%_locale/shop/order/revise/%%token/pay
            controller: 'CoreShop\Bundle\PayumBundle\Controller\PaymentController::prepareCaptureAction'
            variables: '_locale,token'
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 3
            creationDate: 1688643688
            modificationDate: 1688643688
