pimcore_static_routes:
    definitions:
        coreshop_login:
            name: coreshop_login
            pattern: /(\w+)\/shop\/login$/
            reverse: /%_locale/shop/login
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\SecurityController::loginAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643688
            modificationDate: 1688643688
