pimcore_static_routes:
    definitions:
        coreshop_customer_settings:
            name: coreshop_customer_settings
            pattern: /(\w+)\/shop\/customer\/settings$/
            reverse: /%_locale/shop/customer/settings
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CustomerController::settingsAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643689
            modificationDate: 1688643689
