pimcore_static_routes:
    definitions:
        coreshop_category_list:
            name: coreshop_category_list
            pattern: '/(\w+)\/shop\/(.*?)\~c([0-9]+)$/'
            reverse: /%%_locale/shop/%%name~c%category
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CategoryController::indexAction'
            variables: '_locale,name,category'
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643688
            modificationDate: 1688643688
