pimcore_static_routes:
    definitions:
        coreshop_cart_create_named:
            name: coreshop_cart_create_named
            pattern: '/(\w+)\/shop\/cart\/create$/'
            reverse: /%%_locale/shop/cart/create
            controller: 'coreshop.storage_list.controller_multi_list.order::createNamedStorageListAction'
            variables: '_locale'
            defaults: null
            siteId: {  }
            methods:
                - POST
                - GET
            priority: 3
            creationDate: 1686468793
            modificationDate: 1686468793
