pimcore_static_routes:
    definitions:
        coreshop_order_revise:
            name: coreshop_order_revise
            pattern: '/(\w+)\/shop\/order\/revise\/(.*)$/'
            reverse: /%%_locale/shop/order/revise/%%token
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\OrderController::reviseAction'
            variables: '_locale,token'
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643688
            modificationDate: 1688643688
