pimcore_static_routes:
    definitions:
        coreshop_partial_wishlist_add:
            name: coreshop_partial_wishlist_add
            pattern: '/(\w+)\/_partial\/wishlist\/add\/([0-9]+)$/'
            reverse: /%%_locale/_partial/wishlist/add/%%product
            controller: 'coreshop.storage_list.controller.wishlist::addItemAction'
            variables: '_locale,product'
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 3
            creationDate: 1688643689
            modificationDate: 1688643689
