pimcore_static_routes:
    definitions:
        coreshop_cart_create_quote:
            name: coreshop_cart_create_quote
            pattern: /(\w+)\/shop\/cart\/quote$/
            reverse: /%_locale/shop/cart/quote
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CartController::createQuoteAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 3
            creationDate: 1688643688
            modificationDate: 1688643688
