pimcore_static_routes:
    definitions:
        coreshop_customer_orders:
            name: coreshop_customer_orders
            pattern: /(\w+)\/shop\/customer\/orders$/
            reverse: /%_locale/shop/customer/orders
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CustomerController::ordersAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643689
            modificationDate: 1688643689
