pimcore_static_routes:
    definitions:
        coreshop_customer_order_detail:
            name: coreshop_customer_order_detail
            pattern: '/(\w+)\/shop\/customer\/order\/([0-9]+)$/'
            reverse: /%%_locale/shop/customer/order/%%order
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\CustomerController::orderDetailAction'
            variables: '_locale,order'
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643689
            modificationDate: 1688643689
