pimcore_static_routes:
    definitions:
        coreshop_payment:
            name: coreshop_payment
            pattern: '/(\w+)\/shop\/pay\/([0-9]+)$/'
            reverse: /%%_locale/shop/pay/%%order
            controller: 'CoreShop\Bundle\PayumBundle\Controller\PaymentController::prepareCaptureAction'
            variables: '_locale,order'
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 2
            creationDate: 1688643688
            modificationDate: 1688643688
