pimcore_static_routes:
    definitions:
        coreshop_customer_password_reset:
            name: coreshop_customer_password_reset
            pattern: /(\w+)\/shop\/password-reset$/
            reverse: /%_locale/shop/password-reset
            controller: 'CoreShop\Bundle\FrontendBundle\Controller\RegisterController::passwordResetAction'
            variables: _locale
            defaults: null
            siteId: {  }
            methods: {  }
            priority: 5
            creationDate: 1688643689
            modificationDate: 1688643689
